[package]
name = "asayake"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
komorebi-client = { git = "https://github.com/LGUG2Z/komorebi", tag = "v0.1.28" }
serde = "1.0.204"
serde_json = "1.0.121"
winput = "0.2.5"
