name: Rust Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
        - x86_64-pc-windows-msvc
        include:
        - target: x86_64-pc-windows-msvc
          os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust toolchain and cli
      run: |
        rustup target add ${{ matrix.target }}
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v0-rust-${{ matrix.target }}"
    - uses: cargo-bins/cargo-binstall@c635ad6f957466c7818a18cb88570757ee1002b3
    - name: Install depends via cargo-install
      run: |
            cargo binstall tauri-cli --no-confirm
            cargo binstall trunk --locked --no-confirm
    - name: Build
      run: cargo tauri build --verbose --ci -- --release
    - name: Upload artifacts(Windows)
      uses: actions/upload-artifact@v4
      if: matrix.os == 'windows-latest'
      with:
        name: nighty-${{ github.sha }}-${{ matrix.target }}
        path: ./target/release/asayake.exe
#    - name: Upload artifacts(not Windows)
#      uses: actions/upload-artifact@v4
#      if: matrix.os != 'windows-latest'
#      with:
#        name: nighty-${{ github.sha }}-${{ matrix.target }}
#        path: ./target/release/
